name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch where your site is hosted
    paths-ignore:
      - '**/*.json'  # This ignores changes to any .json files

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust this if your built files are in a different folder
